"""CAT-Loss War Room - AI-powered catastrophic loss litigation research."""

from war_room.bootstrap import BootstrapContext, bootstrap_runtime, discover_repo_root
from war_room.cache_io import cached_call
from war_room.models import (
    CaseLawPack,
    CaseIntake,
    CarrierDocPack,
    CitationVerifyPack,
    EvidenceItem,
    ExportArtifact,
    MemoClaim,
    MemoRenderInput,
    QuerySpec,
    ReviewEvent,
    RunAuditSnapshot,
    WeatherBrief,
    adapt_case_intake,
    adapt_caselaw_pack,
    adapt_carrier_doc_pack,
    adapt_citation_verify_pack,
    adapt_query_plan,
    adapt_query_spec,
    adapt_run_audit_snapshot,
    adapt_weather_brief,
    case_intake_to_payload,
    caselaw_pack_to_payload,
    carrier_doc_pack_to_payload,
    citation_verify_pack_to_payload,
    memo_render_input_from_parts,
    query_plan_to_payloads,
    query_spec_to_payload,
    run_audit_snapshot_from_memo_input,
    run_audit_snapshot_from_parts,
    run_audit_snapshot_to_payload,
    weather_brief_to_payload,
)
from war_room.query_plan import (
    CASE_INTAKE_ALLOWED_FIELDS,
    CASE_INTAKE_OPTIONAL_FIELDS,
    CASE_INTAKE_REQUIRED_FIELDS,
    IntakeValidationError,
    generate_query_plan,
    load_case_intake,
    validate_case_intake_payload,
)
from war_room.settings import FeatureFlags, RuntimeEnvironment, WarRoomSettings, load_settings
from war_room.source_scoring import score_url

__all__ = [
    "BootstrapContext",
    "bootstrap_runtime",
    "cached_call",
    "discover_repo_root",
    "FeatureFlags",
    "load_settings",
    "RuntimeEnvironment",
    "score_url",
    "CASE_INTAKE_REQUIRED_FIELDS",
    "CASE_INTAKE_OPTIONAL_FIELDS",
    "CASE_INTAKE_ALLOWED_FIELDS",
    "CaseIntake",
    "IntakeValidationError",
    "QuerySpec",
    "generate_query_plan",
    "validate_case_intake_payload",
    "load_case_intake",
    "WeatherBrief",
    "CarrierDocPack",
    "CaseLawPack",
    "CitationVerifyPack",
    "EvidenceItem",
    "ExportArtifact",
    "MemoClaim",
    "MemoRenderInput",
    "ReviewEvent",
    "RunAuditSnapshot",
    "adapt_case_intake",
    "adapt_query_plan",
    "adapt_query_spec",
    "adapt_run_audit_snapshot",
    "adapt_weather_brief",
    "adapt_carrier_doc_pack",
    "adapt_caselaw_pack",
    "adapt_citation_verify_pack",
    "case_intake_to_payload",
    "query_plan_to_payloads",
    "query_spec_to_payload",
    "run_audit_snapshot_from_memo_input",
    "run_audit_snapshot_from_parts",
    "run_audit_snapshot_to_payload",
    "weather_brief_to_payload",
    "carrier_doc_pack_to_payload",
    "caselaw_pack_to_payload",
    "citation_verify_pack_to_payload",
    "memo_render_input_from_parts",
    "WarRoomSettings",
]
